### ISSUE TITLE
Add attribution data.

### ISSUE THREAD

**Issue by jklmnn** [offenesdresden/ParkAPI#125]
Add attribution data to each city.

**Comment by sibbl** [comment]
To move the conversation from slack to this issue, here's a short summary of my proposal:

I'd suggest to add an optional field `attribution` to each city:

    "attribution": {
        "name": "string",
        "url": "string"
    }

For simplicity I'd only add two fields `name` (required) and `url` (optional). I'd just leave it very basic as the content might change per city and `name` should be as generic as possible so that we can add license names, copyright holders, creators etc. If a URL to a license or a specific site is available, it can be added as well.

Each app and the website should be updated as well, maybe we can make the data source a bit more prominent generally as the first question when someone uses the app the first time often appears to be "where do you get the data from?".

**Comment by kiliankoe** [comment]
How do you guys suggest we should display this in the apps? Any good ideas?

**Comment by jklmnn** [comment]
I think displaying in the apps can be app specific. I would add it to the about page in my app.  
On the website I would add it to the licenses.

**Comment by jklmnn** [comment]
Do we want to add this to:

* index:
  - Pro: all attributions without loading all cities
  - Con: attribution not bound directly to city data
* city data:
  - Pro: attribution directly bound to city data
  - Con: need to load all cities to get all attribution data
* both:
  - Pro: both of other pros, none of their cons
  - Con: redundancy

?

**Comment by kiliankoe** [comment]
What about in the index, but for each city? I though that was the general idea all along?

```js
{
  "api_version": "1.0",
  "cities": {
    "Bonn": {
      "active_support": false,
      "coords": {
        "lat": 50.73438,
        "lng": 7.09548
      },
      "name": "Bonn",
      "source": "http://www.bcp-bonn.de",
      "url": "http://www.bcp-bonn.de",
      "attribution": {
        "name": "...",
        "url": "...",
        "license": "..."
      }
    },
    "Dresden": {
      "active_support": true,
      "coords": {
        "lat": 51.05089,
        "lng": 13.73832
      },
      "name": "Dresden",
      "source": "https://apps.dresden.de/ords/f?p=1110",
      "url": "https://www.dresden.de/parken",
      "attribution": {
        "name": "...",
        "url": "...",
        "license": "..."
      }
    },
    [...]
```

**Comment by mandsch** [comment]
Hi, 
I'm in charge of providing the data for a city and just wanted to add my 2ct to the discussion. When using data provided under dl-de-by-20, the attribution shall be shown when the data is shown. For the map I would expect to find it in the attribution control (e.g. in leaflet or OL), for the list view I guess a similar place should be available or (if easier to implement) on each detail view of a parking lot.

**Comment by sibbl** [comment]
1. I still don't get the difference between `name` and `license` and why we don't put it in one field that's generic enough to include everything we need there instead of splitting and up and ending in the discussion on what to put into `name` and into `license` for new data sources.
2. in the apps, I'd either put it on the map (like @mansch said) or show an information/details icon on the map if there's not enough space. Currently I show the cities and URLs in the "more info" popup under "where's the data from" but placing it more prominent is a good idea I think.
3. For the data format, I vote for `index` or `both`. I'd think it's good to have global information available immediately without a request to each city.

**Comment by jklmnn** [comment]
I find the difference between license and name pretty clear, eg the comment above: name: mandsch, license: dl-de-by-20. If no license is provided we could omit this field.  
@mandsch: The web page footer contains a link to the license page and the maps have an attribution filed in the lower left corner. I would put all attributions on the license page and also show the attribution for the current city in the lower left corner on the map (only on the map page).  
About the Android app: Since I'm currently reworking the design to use the navigation drawer, I'm going to include this in this new design somewhere (probably in the header of the navigation drawer while also showing the current city there.

**Comment by mandsch** [comment]
@JK, thanks for the feedback. That's exactly what I was looking for. Good
to see our data being used in this project.
Am 28.06.2016 16:24 schrieb "JK" <notifications@github.com>:

**Comment by jk** [comment]
@mandsch I'm not the one you want to mention. Perhaps you want to try again.

**Comment by jklmnn** [comment]
OT: It seems that GitHub does not include my username into its emails...

**Comment by jklmnn** [comment]
New suggestion:

    "attribution":{
      "contributor":"<name/desgination of contributor>",
      "url":"<url of contributor or data source>",
      "license":"<license of data>"
    }

**Comment by kiliankoe** [comment]
Let's make all fields optional and it won't be such a big deal 😉

**Comment by jklmnn** [comment]
So should attribution then be also optional or empty? ;)

**Comment by kiliankoe** [comment]
obviously optional, although it wouldn't make much sense having it with nothing inside 😜

**Comment by jklmnn** [comment]
Well more null than optional since the server defaults to null for not given (optional) values.

**Comment by jklmnn** [comment]
I have created a pull request: https://github.com/offenesdresden/ParkAPI/pull/127.

**Comment by kiliankoe** [comment]
I'm guessing this can be closed now?

**Comment by jklmnn** [comment]
Yep, since it's merged and online already.
