### ISSUE TITLE
[Basel] Data

### ISSUE THREAD

**Issue by kiliankoe** [offenesdresden/ParkAPI#35]
http://www.parkleitsystem-basel.ch/stadtplan.php

**Comment by jb3-2** [comment]
How can I help integrating Basel data?

**Comment by jklmnn** [comment]
Our way to go for city data are the modules located at `park_api/cities`. Each city consists of a python module and a geojson file. The python module implements an API that is fed with the HTML and returns the in memory data structure. The geojson file contains static meta data e.g. parking lot coordinates, street addresses etc. I'd recommend to take a look at [Sample_City.py](https://github.com/offenesdresden/ParkAPI/blob/master/park_api/cities/Sample_City.py) and [Sample_City.geojson](https://github.com/offenesdresden/ParkAPI/blob/master/park_api/cities/Sample_City.geojson?short_path=ab38357).
The `properties` key in the geojson file is required while the features are more or less optional (if you get all the data you need from the API you can completely omit it, you can also add custom data to the features, e.g. mappings from parking lot id to parking lot name).
You can simply copy the `Sample_City` files and rename them to `Basel` (which should enable them to be used automatically) and start fiddling around.
If you have any questions or need help, feel free to ask!

**Comment by jklmnn** [comment]
I've taken a quick look into Basels dataset and it isn't too different to the one Zürich uses. I think the best way would be to copy Zürich. Adapting the parser looks like just changing some tags and delimiters (it's both RSS after all). The most time consuming part is probably the creation of a geojson file including coordinates, addresses etc.
Please note while the applications won't break without proper coordinates their use is quite limited (the map will stay empty and the apps won't tell you the nearest parking lot for obvious reasons).

**Comment by jklmnn** [comment]
Another important information that just came into my mind is the number of total parking spots. We usually decide the "goodness" of a parking lot for drivers on the relative occupation (50 free lots on a 1000 lot space indicate that there is a general high demand and you probably want to go somewhere else while 50 free of 50 tells you everything is fine). I noticed that there is at least one parking space that has a changing total capacity ([Badischer Bahnhof](http://www.parkleitsystem-basel.ch/parkhaus/badbahnhof.php)). Since we considered the total amount static data I'm not sure how to map that correctly. I see four options:
 - using the lower count always, this will falsely tell people that it is overflowing on weekends
 - using the higher count always, this will lead people falsely to the parking lot on weekdays
 - storing the total amount for each day, while this is possible due to the current database scheme (at least I think so, @kiliankoe what's your thought on this?) we might still have to put both values into the geojson and then decide at the given time since the live feed doesn't contain this data
 - completely omitting this parking lot

**Comment by jb3-2** [comment]
@jklmnn @kiliankoe I'm right now adding the Basel data. In order not to break the current system I will add a "total", plus a "total_mo", "total_tue", ... "total_sun" number to the geojson file. "Total will contain the Mo-Fr number (100) instead of the weekend number (750). Can you work with that? Thanks!

**Comment by kiliankoe** [comment]
I think that might be the best option for now. We'll have to accommodate somehow, although I'm unsure how at this point. 
I don't know how many lots (of those we would hopefully be adding and supporting in the future) share similar behavior, but it would probably make sense to think about generalizing this somehow. I feel it's very unlikely that total counts will only vary based on the weekday, there might be seasonal changes or something completely different as well.

**Comment by jklmnn** [comment]
I would handle the total amount as dynamic data equally to the free amount. This gives us the freedom to have any total amount at any given time without needing to implement complex rules for how the total amount can change.

**Comment by jklmnn** [comment]
https://parkendd.de/map.html#Basel
Basel is online!
@jb3-2 do you have any Twitter handle you want to be mentioned? I would announce the availability of Basel on Twitter.

**Comment by jklmnn** [comment]
One thing left, I was a little too fast when reviewing the PR:
The weekday handling in [`geodata.py:111`](https://github.com/offenesdresden/ParkAPI/blob/1ce2270962d7c6b919211fac54eb72ef338b7d57/park_api/geodata.py#L111) should probably go to `Basel.py` since it is specific for this city and could possibly interfere with other cities (if someone else is going to use those JSON keys).

**Comment by jb3-2** [comment]
Big thanks for merging! I'm very excited to see our data on the map. 
Yes, you are correct about where to handle weekday special totals. I will look at how we could refactor this with my colleague @nim-stata.

**Comment by jb3-2** [comment]
Sharing on twitter would be great, thanks! Could you mention me (@jonasbieri) and my colleague @JonEck82 accompanied with our hastag #opendataBS?

**Comment by jklmnn** [comment]
Done: https://twitter.com/parken_dd/status/1093563057303965696?s=19

**Comment by jklmnn** [comment]
Since Basel is integrated I'd close this issue now. If there are any problems just reopen it.

**Comment by jklmnn** [comment]
@jb3-2 Basels [RSS feed](http://www.parkleitsystem-basel.ch/rss_feed.php) doesn't seem to be an RSS feed anymore. Is the original feed somewhere available? Otherwise we have to build a new scraper.

**Comment by jb3-2** [comment]
Thanks for letting me know - the RSS feed should be up again soon, it was somehow lost when setting up the new website https://www.parkleitsystem-basel.ch/.

**Comment by jb3-2** [comment]
The RSS Feed URL is now live here: https://www.parkleitsystem-basel.ch/alte_site/rss_feed.php

Can you please change that? Thanks so much!

**Comment by kiliankoe** [comment]
If the domain is the same, would it not make sense to host it one directory higher and therefore under the same URL (which in the filename says it should be an RSS feed anyways ;)) at http://www.parkleitsystem-basel.ch/rss_feed.php

**Comment by jklmnn** [comment]
It seems http://www.parkleitsystem-basel.ch/rss_feed.php already redirects to https://www.parkleitsystem-basel.ch/alte_site/rss_feed.php. Is this a permanent solution @jb3-2 (at least it's a permanent redirect)?

**Comment by jb3-2** [comment]
Ah good, they have now set up a redirect. It should be stable until further
notice. I hope to get a heads up if they change anything next time...

Am Mo., 4. Nov. 2019 um 18:08 Uhr schrieb JK <notifications@github.com>:

**Comment by jklmnn** [comment]
Thanks for the info. I'd consider this fixed now. If there arise any problems or changes, please reopen the issue.
