### ISSUE TITLE
IDs?

### ISSUE THREAD

**Issue by kiliankoe** [offenesdresden/ParkAPI#65]
@jklmnn suggested that we remove city IDs alltogether and reference them by their real name only. Not quite sure how we'd deal with duplicates, but due to the current metadata format we'd run into this problem anyways. But otherwise it would make things much easier.

Any suggestions?

**Comment by jklmnn** [comment]
:+1:

**Comment by kiliankoe** [comment]
I know we've scrapped this idea since, but didn't we agree to switch things around? I remember @sibbl having some valid input on this, probably in our slack, so I don't remember much :D 

Anybody remember what we wanted to do here?

**Comment by sibbl** [comment]
We first had a dict `[{"somename": "id"}, {"somename2": "id2"}, ... ]` which is now a more complex object like `[{"id": {"name": "somename", ...}, "id2": { "name": "somename2"}, ...]`. In the first version, the name would have to be unique as it was the key of the dict, but now this is already fixed in my eyes, isn't it? There's a unique ID for each city (which can equal to the name) and a name inside the value of each dict row.

**Comment by kiliankoe** [comment]
👍: Thanks!
